name: Run Tweet Watcher

on:
  #schedule:
  #  - cron: "*/5 * * * *"  # 5分ごとに実行
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" | base64 -d > $HOME/firebase-key.json

      - name: Debug Firebase file
        run: |
          echo "HOME: $HOME"
          echo "File exists: $(test -f $HOME/firebase-key.json && echo 'YES' || echo 'NO')"
          ls -la $HOME/firebase-key.json || echo "File not found"
          echo "First few chars of file:"
          head -c 100 $HOME/firebase-key.json || echo "Cannot read file"

      - name: Run tweet watcher script
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.FG_PAT_SCRAPCAST }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GOOGLE_APPLICATION_CREDENTIALS: "$HOME/firebase-key.json"
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python tweet_watcher.py
