# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" | base64 -d > $HOME/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"

      - name: Run script with Firestore access
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$HOME/firebase-key.json"
        run: |
          echo "${HOME}"
          head -2 "$HOME/firebase-key.json"

      # Runs a single command using the runners shell
      - shell: bash
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          VAR_TEST: ${{ vars.VAR_TEST }}
          GITHUB_TOKEN: ${{ secrets.FG_PAT_SCRAPCAST }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          #example-command "$BEARER_TOKEN"
          echo "${BEARER_TOKEN}"
          echo "${VAR_TEST}"
          echo "${GITHUB_TOKEN}"
          echo "${GITHUB_REPOSITORY}"
          echo "${GH_PAT}"
